export const LICENSE_CONSTANTS = {
  GRACE_PERIOD_HOURS: 72,
  DEFAULT_MAX_DEVICES: 1,
  KEY_PREFIX: 'TOFU',
  KEY_SEGMENT_LENGTH: 4,
  KEY_RANDOM_BYTES: 16,
} as const;

export const LICENSE_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
} as const;

export const LICENSE_ACTIONS = {
  LICENSE_CREATE_ATTEMPT: 'LICENSE_CREATE_ATTEMPT',
  LICENSE_CREATED: 'LICENSE_CREATED',
  LICENSE_SUSPENDED: 'LICENSE_SUSPENDED',
  DEVICE_ACTIVATED: 'DEVICE_ACTIVATED',
  DEVICE_REACTIVATED: 'DEVICE_REACTIVATED',
  DEVICE_DEACTIVATED: 'DEVICE_DEACTIVATED',
  DEVICE_AUTO_DEACTIVATED: 'DEVICE_AUTO_DEACTIVATED',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
} as const;

export const ERROR_CODES = {
  LICENSE_NOT_FOUND: 'LICENSE_NOT_FOUND',
  LICENSE_NOT_ACTIVE: 'LICENSE_NOT_ACTIVE',
  LICENSE_EXPIRED: 'LICENSE_EXPIRED',
  DEVICE_NOT_ACTIVATED: 'DEVICE_NOT_ACTIVATED',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  FINGERPRINT_MISMATCH: 'FINGERPRINT_MISMATCH',
  INVALID_LICENSE_KEY: 'INVALID_LICENSE_KEY',
  MISSING_WEBHOOK_SIGNATURE: 'MISSING_WEBHOOK_SIGNATURE',
  MISSING_RAW_BODY: 'MISSING_RAW_BODY',
  MISSING_EMAIL_IN_PAYMENT: 'MISSING_EMAIL_IN_PAYMENT',
  WEBHOOK_PROCESSING_ERROR: 'WEBHOOK_PROCESSING_ERROR',
} as const;

export const THROTTLE_LIMITS = {
  ACTIVATE: { limit: 5, ttl: 60000 },
  VERIFY: { limit: 30, ttl: 60000 },
  DEACTIVATE: { limit: 10, ttl: 60000 },
  INFO: { limit: 20, ttl: 60000 },
} as const;

export const STRIPE_API_VERSION = '2025-11-17.clover' as const;
