export const LICENSE_CONSTANTS = {
  GRACE_PERIOD_HOURS: 72,
  DEFAULT_MAX_DEVICES: 2,
  ADMIN_DEFAULT_MAX_DEVICES: 3,
  KEY_PREFIX: 'TOFU',
  KEY_SEGMENT_LENGTH: 4,
  KEY_RANDOM_BYTES: 16,
} as const;

export const LICENSE_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  REFUNDED: 'REFUNDED',
} as const;

export const LICENSE_ACTIONS = {
  LICENSE_CREATE_ATTEMPT: 'LICENSE_CREATE_ATTEMPT',
  LICENSE_CREATED: 'LICENSE_CREATED',
  LICENSE_CREATED_BY_ADMIN: 'LICENSE_CREATED_BY_ADMIN',
  LICENSE_SUSPENDED: 'LICENSE_SUSPENDED',
  LICENSE_REFUNDED: 'LICENSE_REFUNDED',
  LICENSE_STATUS_CHANGED: 'LICENSE_STATUS_CHANGED',
  DEVICE_ACTIVATED: 'DEVICE_ACTIVATED',
  DEVICE_REACTIVATED: 'DEVICE_REACTIVATED',
  DEVICE_DEACTIVATED: 'DEVICE_DEACTIVATED',
  DEVICE_AUTO_DEACTIVATED: 'DEVICE_AUTO_DEACTIVATED',
  DEVICE_REMOVED_BY_ADMIN: 'DEVICE_REMOVED_BY_ADMIN',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
} as const;

export const ERROR_CODES = {
  LICENSE_NOT_FOUND: 'LICENSE_NOT_FOUND',
  LICENSE_NOT_ACTIVE: 'LICENSE_NOT_ACTIVE',
  LICENSE_EXPIRED: 'LICENSE_EXPIRED',
  DEVICE_NOT_ACTIVATED: 'DEVICE_NOT_ACTIVATED',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  FINGERPRINT_MISMATCH: 'FINGERPRINT_MISMATCH',
  INVALID_LICENSE_KEY: 'INVALID_LICENSE_KEY',
  INVALID_DEVICE_ID: 'INVALID_DEVICE_ID',
  DEVICE_LIMIT_REACHED: 'DEVICE_LIMIT_REACHED',
  MISSING_WEBHOOK_SIGNATURE: 'MISSING_WEBHOOK_SIGNATURE',
  MISSING_RAW_BODY: 'MISSING_RAW_BODY',
  MISSING_EMAIL_IN_PAYMENT: 'MISSING_EMAIL_IN_PAYMENT',
  REFUND_WITHOUT_PAYMENT_INTENT: 'REFUND_WITHOUT_PAYMENT_INTENT',
  ADMIN_KEY_NOT_CONFIGURED: 'ADMIN_KEY_NOT_CONFIGURED',
  INVALID_AUTHORIZATION_HEADER: 'INVALID_AUTHORIZATION_HEADER',
  INVALID_ADMIN_KEY: 'INVALID_ADMIN_KEY',
} as const;

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LICENSE_LIMIT: 50,
  DEVICE_LIMIT: 50,
  LOG_LIMIT: 100,
  SEARCH_LIMIT: 20,
} as const;

export const THROTTLE_LIMITS = {
  ACTIVATE: { limit: 5, ttl: 60000 },
  VERIFY: { limit: 30, ttl: 60000 },
  DEACTIVATE: { limit: 10, ttl: 60000 },
  INFO: { limit: 20, ttl: 60000 },
};

export const STRIPE_CONFIG = {
  API_VERSION: '2025-11-17.clover',
  UNPROCESSED_PAYMENTS_DAYS: 7,
} as const;
