export const ErrorCodes = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ALREADY_HAVE_SUBSCRIPTION: 'ALREADY_HAVE_SUBSCRIPTION',
  NO_ACTIVE_SUBSCRIPTION: 'NO_ACTIVE_SUBSCRIPTION',
  SUBSCRIPTION_ALREADY_CANCELLED: 'SUBSCRIPTION_ALREADY_CANCELLED',
  NO_CANCELLABLE_SUBSCRIPTION: 'NO_CANCELLABLE_SUBSCRIPTION',
  VIDEO_TOO_LONG_FOR_FREE: 'VIDEO_TOO_LONG_FOR_FREE',
  AI_NOT_FOR_FREE: 'AI_NOT_FOR_FREE',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_REACTIVATED: 'SUBSCRIPTION_REACTIVATED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

